// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiUsersByIdData, DeleteApiUsersByIdErrors, DeleteApiUsersByIdResponses, GetApiMeData, GetApiMeResponses, GetApiUsersData, GetApiUsersErrors, GetApiUsersResponses, GetConnectAuthorizeData, GetConnectAuthorizeResponses, GetConnectLogoutData, GetConnectLogoutResponses, PostApiUsersData, PostApiUsersErrors, PostApiUsersResponses, PostConnectAuthorizeData, PostConnectAuthorizeResponses, PostConnectLogoutData, PostConnectLogoutResponses, PostConnectTokenData, PostConnectTokenResponses, PutApiUsersByIdData, PutApiUsersByIdErrors, PutApiUsersByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiMe = <ThrowOnError extends boolean = false>(options?: Options<GetApiMeData, ThrowOnError>) => (options?.client ?? client).get<GetApiMeResponses, unknown, ThrowOnError>({ url: '/api/me', ...options });

export const getConnectAuthorize = <ThrowOnError extends boolean = false>(options?: Options<GetConnectAuthorizeData, ThrowOnError>) => (options?.client ?? client).get<GetConnectAuthorizeResponses, unknown, ThrowOnError>({ url: '/connect/authorize', ...options });

export const postConnectAuthorize = <ThrowOnError extends boolean = false>(options?: Options<PostConnectAuthorizeData, ThrowOnError>) => (options?.client ?? client).post<PostConnectAuthorizeResponses, unknown, ThrowOnError>({ url: '/connect/authorize', ...options });

export const getConnectLogout = <ThrowOnError extends boolean = false>(options?: Options<GetConnectLogoutData, ThrowOnError>) => (options?.client ?? client).get<GetConnectLogoutResponses, unknown, ThrowOnError>({ url: '/connect/logout', ...options });

export const postConnectLogout = <ThrowOnError extends boolean = false>(options?: Options<PostConnectLogoutData, ThrowOnError>) => (options?.client ?? client).post<PostConnectLogoutResponses, unknown, ThrowOnError>({ url: '/connect/logout', ...options });

export const postConnectToken = <ThrowOnError extends boolean = false>(options?: Options<PostConnectTokenData, ThrowOnError>) => (options?.client ?? client).post<PostConnectTokenResponses, unknown, ThrowOnError>({ url: '/connect/token', ...options });

export const getApiUsers = <ThrowOnError extends boolean = false>(options?: Options<GetApiUsersData, ThrowOnError>) => (options?.client ?? client).get<GetApiUsersResponses, GetApiUsersErrors, ThrowOnError>({ url: '/api/users', ...options });

export const postApiUsers = <ThrowOnError extends boolean = false>(options: Options<PostApiUsersData, ThrowOnError>) => (options.client ?? client).post<PostApiUsersResponses, PostApiUsersErrors, ThrowOnError>({
    url: '/api/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiUsersById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiUsersByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiUsersByIdResponses, DeleteApiUsersByIdErrors, ThrowOnError>({ url: '/api/users/{id}', ...options });

export const putApiUsersById = <ThrowOnError extends boolean = false>(options: Options<PutApiUsersByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiUsersByIdResponses, PutApiUsersByIdErrors, ThrowOnError>({
    url: '/api/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
