// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5009/' | (string & {});
};

export type CreateUserDto = {
    email: string;
    password: string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type UpdateUserDto = {
    email: null | string;
    newPassword: null | string;
};

export type UserListDto = {
    id: string;
    email: string;
    emailConfirmed: boolean;
};

export type GetApiMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type GetApiMeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetConnectAuthorizeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connect/authorize';
};

export type GetConnectAuthorizeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostConnectAuthorizeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connect/authorize';
};

export type PostConnectAuthorizeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetConnectLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connect/logout';
};

export type GetConnectLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostConnectLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connect/logout';
};

export type PostConnectLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostConnectTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connect/token';
};

export type PostConnectTokenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type GetApiUsersErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type GetApiUsersError = GetApiUsersErrors[keyof GetApiUsersErrors];

export type GetApiUsersResponses = {
    /**
     * OK
     */
    200: Array<UserListDto>;
};

export type GetApiUsersResponse = GetApiUsersResponses[keyof GetApiUsersResponses];

export type PostApiUsersData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type PostApiUsersErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostApiUsersError = PostApiUsersErrors[keyof PostApiUsersErrors];

export type PostApiUsersResponses = {
    /**
     * Created
     */
    201: UserListDto;
};

export type PostApiUsersResponse = PostApiUsersResponses[keyof PostApiUsersResponses];

export type DeleteApiUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type DeleteApiUsersByIdErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiUsersByIdError = DeleteApiUsersByIdErrors[keyof DeleteApiUsersByIdErrors];

export type DeleteApiUsersByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiUsersByIdResponse = DeleteApiUsersByIdResponses[keyof DeleteApiUsersByIdResponses];

export type PutApiUsersByIdData = {
    body: UpdateUserDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type PutApiUsersByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiUsersByIdError = PutApiUsersByIdErrors[keyof PutApiUsersByIdErrors];

export type PutApiUsersByIdResponses = {
    /**
     * OK
     */
    200: UserListDto;
};

export type PutApiUsersByIdResponse = PutApiUsersByIdResponses[keyof PutApiUsersByIdResponses];
